### ISSUE TITLE
Rapido hotend not supported?

### ISSUE THREAD

**Issue by JiMcNulty** [Evan10E/Voron-FCC-Toolhead-Board#4]
The Toolboard is rated for 100W hotend but rapido is 115W

**Comment by Evan10E** [comment]
This is a limitation of the actual FFC ribbon, not my toolhead board. If you manage to find a ribbon cable capable of handling more power, the board should be compatible with 115W. You could probably still get away with the original cables if your heater isn't allowed to have 100% power and instead you pwm the power.
